/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sdmessage.proto */

#ifndef PROTOBUF_C_sdmessage_2eproto__INCLUDED
#define PROTOBUF_C_sdmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Entry Entry;
typedef struct _Entry__Data Entry__Data;


/* --- enums --- */


/* --- messages --- */

struct  _Entry__Data
{
  ProtobufCMessage base;
  int32_t datasize;
  char *value;
};
#define ENTRY__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&entry__data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _Entry
{
  ProtobufCMessage base;
  char *key;
  Entry__Data *data;
};
#define ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&entry__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


/* Entry__Data methods */
void   entry__data__init
                     (Entry__Data         *message);
/* Entry methods */
void   entry__init
                     (Entry         *message);
size_t entry__get_packed_size
                     (const Entry   *message);
size_t entry__pack
                     (const Entry   *message,
                      uint8_t             *out);
size_t entry__pack_to_buffer
                     (const Entry   *message,
                      ProtobufCBuffer     *buffer);
Entry *
       entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   entry__free_unpacked
                     (Entry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Entry__Data_Closure)
                 (const Entry__Data *message,
                  void *closure_data);
typedef void (*Entry_Closure)
                 (const Entry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor entry__descriptor;
extern const ProtobufCMessageDescriptor entry__data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sdmessage_2eproto__INCLUDED */
